boo = ['brain damage',
       'pentil kumbang',
       'redartd',
       'bagogo',
       'uganda',
       'Jokowi Dodowi',
       'ortu lu kecewa sama lu',
       'hah',
       'Asep junaedi ama ilham',
       'panda kontol',
       'air asia, more like water asia']