cumzone = ['Welcome to the cum zone',
           'Only cum inside anime girls',
           'Quivering clit, double jointed pussy',
           'Fresh balls, elegant ejaculation',
           'First the kiss, then the cum',
           'My dick is in love with pain',
           'Co-op cock torture',
           'Stuff my dick into a furnace',
           'Stitch my cock shut',
           'Pressure cook my greasy balls',
           'Cumblast me and make it snappy',
           'What\'s all the cummotion?',
           'My dad fell into a cum shaft',
           'My dad glazed my face with cum',
           'Fertilize a baby with hunk spunk',
           'Cum spunk in my trunk',
           'Cum craving toddler',
           'Cum drippin\' cunt',
           'Cummy Rae Jepsen',
           'Cum me maybe',
           'Cummy bottom boy',
           'Night of the living cum',
           'Nefarious cum mastermind',
           'Cum makes me fearless',
           'Cum crammer, cock slammer',
           'Cum slammed ya mum',
           'Mail your mums pieces of my dick',
           'Bazinga!',
           'Chug the cum',
           'fug ya mum',
           'Fuck my asshole full of cum',
           'Three little words',
           'Get fucked, nerd',
           'Cum stuffer, '
           'jenkem huffer',
           'Fuck my cum puddle',
           'Bottom stuffer',
           'semen huffer',
           'Would love a gator to fuck me',
           'Undercooked baby pig penises',
           'Help my dogs get a huge boner',
           'Water bong full of cat cum',
           'Accidentally fucked my own ass',
           'I barely had any dicks inside me',
           'Who ate all my cum? A mystery',
           'Cum detective hot on the trail',
           'Bees make honey, I make cummy']

boo = ['brain damage',
       'pentil kumbang',
       'redartd',
       'bagogo',
       'uganda',
       'Jokowi Dodowi',
       'ortu lu kecewa sama lu',
       'hah',
       'panda kontol',
       'air asia, more like water asia']

shutdowns = ['bacot',
             'kontol',
             'memek',
             'brisik',
             'what',
             'yes',
             'uganda',
             'Æughē',
             'ngapain ping mek',
             'apaan',
             'palkon apaan',
             'Singapura',
             '?']

sauce_respo = ['lmao wtf is this',
               'ok thats actually interesting',
               'wtf',
               'lol where the fuck did you get this',
               'nice',
               'the fuck?',
               'i hope its not yaoi',
               'i can nut to this']

errors = ['fix this shit ',
          'wheres that nerd ',
          'weh bocak goblok, benerin ni ',
          'short fella cmere ',
          'damn, ',
          'wtf did u do, help ',
          'bababoeey ']
